feign:
  client:
    config:
      default:
        connectTimeout: ${FEIGN_DEFAULT_CONNECT_TIMEOUT_MILLS:1500}
        readTimeout: ${FEIGN_DEFAULT_READ_TIMEOUT_MILLS:3000}
        loggerLevel: BASIC

#      PaymentServiceFeignClient:
#        connectTimeout: ${PAYMENT_SERVICE_CONNECT_TIMEOUT_MILLS:1500}
#        readTimeout: ${PAYMENT_SERVICE_READ_TIMEOUT_MILLS:3000}
#        loggerLevel: BASIC

